name: Build and Deploy

# Ensure workflow has write permissions so deployment can push
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Do not persist the automatically provided token in the git config;
          # allow the deploy action to use the token it receives.
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Primary: built-in token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Fallback (uncomment & create secret if GITHUB_TOKEN can't push due to org rules):
          # github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./build
          # optional: customize branch or committer info
          # publish_branch: gh-pages
          # user_name: github-actions[bot]
          # user_email: github-actions[bot]@users.noreply.github.com
