name: Build and Publish to /docs

# Ensure workflow can write back to the repository
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish-docs:
    # skip if the triggering commit is the workflow's own commit (we add [skip ci] when committing)
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare docs folder
        run: |
          # remove previous docs content (keep .git if present)
          rm -rf docs || true
          mkdir -p docs
          cp -a build/. docs/

      - name: Commit and push docs/
        env:
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          git config user.name "${GIT_COMMITTER_NAME}"
          git config user.email "${GIT_COMMITTER_EMAIL}"
          git add -A docs
          if git diff --cached --quiet; then
            echo "No changes to docs; nothing to commit"
          else
            git commit -m "chore(deploy): update docs from build [skip ci]"
            git push origin HEAD:main
          fi
